version: '3.8'

services:
  rwesearch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory to persist data
      - ./data:/app/data
      # Mount saved_models directory to persist trained models
      - ./saved_models:/app/saved_models
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    container_name: rwesearch-app
